### ISSUE TITLE
Conversion from array to tensor error

### ISSUE THREAD

**Issue by Mrinal18** [wangyirui/AD_Prediction#3]
I am getting this error when i am running  main_autoencoder.py. 

`Traceback (most recent call last):
  File "main_autoencoder.py", line 101, in <module>
    main(options)
  File "main_autoencoder.py", line 74, in main
    for i, patches in enumerate(train_loader):
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/Users/science/Desktop/Alziehmer/AD_Prediction/AD_Standard_3DRandomPatch.py", line 42, in __getitem__
    patch_samples = getRandomPatches(image_array)
  File "/Users/science/Desktop/Alziehmer/AD_Prediction/AD_Standard_3DRandomPatch.py", line 80, in getRandomPatches
    img = torch.from_numpy(img)`

`RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.`

Kindly help me solve this?

**Comment by wangyirui** [comment]
@Mrinal18 This line is used for debugging. We want to make sure the image is correct after transforms
