### ISSUE TITLE
Invalid Argument 0 error

### ISSUE THREAD

**Issue by Mrinal18** [wangyirui/AD_Prediction#4]
Hey,

When i run 
` python main_autoencoder.py --batch_size 32 --num_classes 2 --epochs 200 --gpuid -1` 
I get this error:

```
At 0-th epoch.
Traceback (most recent call last):
  File "main_autoencoder.py", line 101, in <module>
    main(options)
  File "main_autoencoder.py", line 74, in main
    for i, patches in enumerate(train_loader):
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 132, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 132, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 135, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 112, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/functional.py", line 66, in stack
    return torch.cat(inputs, dim, out=out)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 7 and 3 in dimension 2 at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:2897

```

Is there anyway you can help me with this?

**Comment by wangyirui** [comment]
@Mrinal18 I am not familiar with this part. But I think your input channel is incorrect. The tensor expect the channel of 3 but got 7, I guess. You may check your input before this line.

**Comment by Mrinal18** [comment]
I am trying but not able to clearly figure it out. 
Will it be possible for you to send me the working code(along with dataset) so that i can look at the internal working of it step by step and change it according to my dataset? 
I know it's hard but i request you if you can help me out
