### ISSUE TITLE
Subscriptable Error

### ISSUE THREAD

**Issue by czainab** [wangyirui/AD_Prediction#7]
F:\VAIO\Latest\AD_Prediction-master\AD_Prediction-master\2D>python main_alextnet.py
2018-05-05 16:00:35 INFO: At 0-th epoch.
Traceback (most recent call last):
  File "main_alextnet.py", line 236, in <module>
    main(options)
  File "main_alextnet.py", line 135, in main
    train_loss, correct_cnt = train(model, train_loader, use_cuda, criterion, optimizer, train_loss_f)
  File "main_alextnet.py", line 160, in train
    for it, train_data in enumerate(train_loader):
  File "C:\Users\Hashim\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\Hashim\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "C:\Users\Hashim\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\Hashim\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "F:\VAIO\Latest\AD_Prediction-master\AD_Prediction-master\2D\AD_2DRandomSlicesData.py", line 56, in __getitem__
    AXimageList = axRandomSlice(image)
  File "F:\VAIO\Latest\AD_Prediction-master\AD_Prediction-master\2D\AD_2DRandomSlicesData.py", line 94, in axRandomSlice
    return getRandomSlice(image_array, NON_AX, AX_F, AX_SCETION)
  File "F:\VAIO\Latest\AD_Prediction-master\AD_Prediction-master\2D\AD_2DRandomSlicesData.py", line 73, in getRandomSlice
    first_p = list(mean_array).index(filter(lambda x: x>0, mean_array)[0])
TypeError: 'filter' object is not subscriptable
I just ran your code with your dataset but I get this type error and unable to figure it out. Kindly help me resolving this error

**Comment by Mrinal18** [comment]
Hello @czainab, can you kindly mail me the dataset too?

**Comment by Mrinal18** [comment]
if you are running it in python3, then filter doesnt return list but an iterable filter object.

So use list before filter and it should work
`first_p = list(mean_array).index(list(filter(lambda x: x>0, mean_array)[0]))`

**Comment by czainab** [comment]
Well I downloaded the images in test, train text file from ADNI website. You can just simply apply for the access.
Thank you for your help but I tried the above solution and it didn't work for me now I am getting another error in the same file on slice_p = int(round(first_p + (last_p - first_p)*fraction)) and the error is TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'
Kindly help me out

**Comment by czainab** [comment]
Can you please guide me how you were able to run this file because I am like getting errors on every line. I just fix one error and got another on the very next line.

**Comment by Mrinal18** [comment]
look at #1, where he explained how to run the code. Kindly tell me if it runs

**Comment by Mrinal18** [comment]
I noticed you are running this using anaconda3 which as python 3+.

kindly try running this using python2.

**Comment by Mrinal18** [comment]
Hey, so i took the access of the ADNI data, can you kindly guide me what to do after that? i cant seem to find the data.

**Comment by czainab** [comment]
After login go to Projects, than ADNI, than click on Download, Image Collection and under Data Collection tab you will find the images.
 

    On Thursday, May 10, 2018 3:05 PM, Mrinal18 <notifications@github.com> wrote:
 

 Hey, so i took the access of the ADNI data, can you kindly guide me what to do after that? i cant seem to find the data.—

**Comment by FaRe3** [comment]
> @czainab , replace it with this
> 
> `first_p = list(mean_array).index(list(filter(lambda x: x>0, mean_array))[0]) `

Did this code worked . Please let me know
thank yoy

**Comment by sankavi05** [comment]
> @czainab , replace it with this
> 
> `first_p = list(mean_array).index(list(filter(lambda x: x>0, mean_array))[0]) `

**Comment by coderHelloWorld** [comment]
> Still getting the same error TypeError: 'filter' object is not subscriptable.

please tell me how to solve this issue, if you have resolved it
